[build]
  type = "static-site"

[[build.command]]
  name = "run"
  command = "echo 'Build started...'"
  working_dir = "."

[[build.command]]
  name = "serve"
  command = "echo 'Serving static files...'"
  working_dir = "."
